### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Companda-SEE/GTM-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values that are then used as your url. These methods take in a single text argument and returns an encoded Uniform Resource Identifier (URI) by escaping special characters. They return a string that represents the provided string encoded as a URI. You should use this method on "compandaAPIendpoint",  "public_key" when generating the url
var url=data.compandaAPIendpoint + public_key + '?debug=' + data.debug;

**Comment by Companda-SEE** [comment]
Thank you for your reply, I have updated the template code to reflect your feedback.
All three user provided values are now wrapped in encodeUri and encodeUriComponent functions.
